import autogenerated.*;
import io.grpc.stub.StreamObserver;

public class CalculatorServiceImpl extends CalculatorServiceGrpc.CalculatorServiceImplBase{
    @Override
    public void add(CalRequest request, StreamObserver<CalResponse> responseObserver) {
        CalResponse response=null;

        //获取两个请求参数
        String first = request.getFirst();
        String second = request.getSecond();
        //相加，拼成返回值
        String result=Integer.parseInt(first)+Integer.parseInt(second)+"";

        //响应
       try{
           response=CalResponse.newBuilder().setResult(result).build();
       }catch (Exception e){
           responseObserver.onError(e);
       }finally {
           responseObserver.onNext(response);
       }
       responseObserver.onCompleted();
    }
}
