// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: calservice.proto

package autogenerated;

public interface CalResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:CalResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string result = 1;</code>
   */
  java.lang.String getResult();
  /**
   * <code>string result = 1;</code>
   */
  com.google.protobuf.ByteString
      getResultBytes();
}
