// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: calservice.proto

package autogenerated;

public interface CalRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:CalRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string first = 1;</code>
   */
  java.lang.String getFirst();
  /**
   * <code>string first = 1;</code>
   */
  com.google.protobuf.ByteString
      getFirstBytes();

  /**
   * <code>string second = 2;</code>
   */
  java.lang.String getSecond();
  /**
   * <code>string second = 2;</code>
   */
  com.google.protobuf.ByteString
      getSecondBytes();
}
